// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieListApp.Models;

#nullable disable

namespace MovieListApp.Migrations
{
    [DbContext(typeof(MovieContext))]
    partial class MovieContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MovieListApp.Models.Genre", b =>
                {
                    b.Property<string>("GenreId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GenreId");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            GenreId = "A",
                            Name = "Action"
                        },
                        new
                        {
                            GenreId = "CD",
                            Name = "Crime Drama"
                        },
                        new
                        {
                            GenreId = "D",
                            Name = "Drama"
                        },
                        new
                        {
                            GenreId = "F",
                            Name = "Fantasy"
                        },
                        new
                        {
                            GenreId = "H",
                            Name = "Horror"
                        },
                        new
                        {
                            GenreId = "M",
                            Name = "Musical"
                        },
                        new
                        {
                            GenreId = "SF",
                            Name = "Science Fiction"
                        });
                });

            modelBuilder.Entity("MovieListApp.Models.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovieId"));

                    b.Property<string>("GenreId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("MovieId");

                    b.HasIndex("GenreId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            GenreId = "H",
                            Name = "Psycho",
                            Rating = 5,
                            Year = 1960
                        },
                        new
                        {
                            MovieId = 2,
                            GenreId = "SF",
                            Name = "The Matrix",
                            Rating = 4,
                            Year = 1999
                        },
                        new
                        {
                            MovieId = 3,
                            GenreId = "SF",
                            Name = "Dune",
                            Rating = 3,
                            Year = 2023
                        },
                        new
                        {
                            MovieId = 4,
                            GenreId = "H",
                            Name = "The Silence of the Lambs",
                            Rating = 5,
                            Year = 1991
                        },
                        new
                        {
                            MovieId = 5,
                            GenreId = "SF",
                            Name = "2001: A Space Odyssey",
                            Rating = 2,
                            Year = 1968
                        },
                        new
                        {
                            MovieId = 6,
                            GenreId = "CD",
                            Name = "The Godfather",
                            Rating = 5,
                            Year = 1972
                        },
                        new
                        {
                            MovieId = 7,
                            GenreId = "A",
                            Name = "Black Panther",
                            Rating = 4,
                            Year = 2018
                        },
                        new
                        {
                            MovieId = 8,
                            GenreId = "SF",
                            Name = "Interstellar",
                            Rating = 4,
                            Year = 2014
                        },
                        new
                        {
                            MovieId = 9,
                            GenreId = "CD",
                            Name = "Pulp Fiction",
                            Rating = 5,
                            Year = 1994
                        },
                        new
                        {
                            MovieId = 10,
                            GenreId = "D",
                            Name = "Parasite",
                            Rating = 2,
                            Year = 2019
                        },
                        new
                        {
                            MovieId = 11,
                            GenreId = "A",
                            Name = "Raiders of the Lost Ark",
                            Rating = 5,
                            Year = 1981
                        },
                        new
                        {
                            MovieId = 12,
                            GenreId = "H",
                            Name = "Get Out",
                            Rating = 5,
                            Year = 2017
                        },
                        new
                        {
                            MovieId = 13,
                            GenreId = "D",
                            Name = "Joker",
                            Rating = 5,
                            Year = 2019
                        },
                        new
                        {
                            MovieId = 14,
                            GenreId = "SF",
                            Name = "Inception",
                            Rating = 5,
                            Year = 2010
                        },
                        new
                        {
                            MovieId = 15,
                            GenreId = "F",
                            Name = "The Fellowship of the Ring",
                            Rating = 5,
                            Year = 2001
                        },
                        new
                        {
                            MovieId = 16,
                            GenreId = "M",
                            Name = "La La Land",
                            Rating = 5,
                            Year = 2016
                        },
                        new
                        {
                            MovieId = 17,
                            GenreId = "A",
                            Name = "The Avengers",
                            Rating = 4,
                            Year = 2012
                        },
                        new
                        {
                            MovieId = 18,
                            GenreId = "SF",
                            Name = "The Terminator",
                            Rating = 3,
                            Year = 1984
                        },
                        new
                        {
                            MovieId = 19,
                            GenreId = "F",
                            Name = "Frozen",
                            Rating = 5,
                            Year = 2013
                        },
                        new
                        {
                            MovieId = 20,
                            GenreId = "SF",
                            Name = "Back to the Future",
                            Rating = 4,
                            Year = 1985
                        },
                        new
                        {
                            MovieId = 21,
                            GenreId = "SF",
                            Name = "Mad Max: Fury Road",
                            Rating = 4,
                            Year = 2015
                        },
                        new
                        {
                            MovieId = 22,
                            GenreId = "SF",
                            Name = "Star Wars: Episode IV - A New Hope",
                            Rating = 2,
                            Year = 1977
                        },
                        new
                        {
                            MovieId = 23,
                            GenreId = "D",
                            Name = "Gladiator",
                            Rating = 5,
                            Year = 2000
                        },
                        new
                        {
                            MovieId = 24,
                            GenreId = "H",
                            Name = "The Dark Knight",
                            Rating = 4,
                            Year = 2008
                        },
                        new
                        {
                            MovieId = 25,
                            GenreId = "D",
                            Name = "The Revenant",
                            Rating = 3,
                            Year = 2015
                        });
                });

            modelBuilder.Entity("MovieListApp.Models.Movie", b =>
                {
                    b.HasOne("MovieListApp.Models.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");
                });
#pragma warning restore 612, 618
        }
    }
}
